version: '3.1'

services:
  relayer-db:
    container_name: relayer-db
    image: postgres:14.9-alpine3.18
    # image: postgres:15-alpine
    restart: always
    # command: postgres -c 'max_connections=20'
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready", "-d", "relayer"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: relayer
    volumes:
      - ./.db:/var/lib/postgresql/data

  relayer:
    container_name: relayer
    build: 
      context: ./
      dockerfile: Dockerfile
    image: "scalarorg/xchains-relayer"
    depends_on:
      relayer-db:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@relayer-db:5432/relayer
    volumes:
      - ./:/app
      - ./.env.${ENV}:/app/.env:Z
      - ./entrypoint.sh:/app/entrypoint.sh
    entrypoint: "sleep infinity"  
    # entrypoint: "/app/entrypoint.sh"
